# GitHub Sponsors and funding platforms
# See https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository

github: laniksj
patreon: laniksj
buy_me_a_coffee: laniksj
custom: ["https://www.paypal.me/laniksj"]
