# Configuration for move-issues - https://github.com/dessant/move-issues
# This action allows moving GitHub issues between repositories with configurable options

# Issue processing options
deleteCommand: true          # Delete the command comment if it contains no other content
closeSourceIssue: true       # Close the source issue after moving to prevent further activity
lockSourceIssue: true        # Lock the source issue to prevent new comments/edits
mentionAuthors: true         # Mention original issue and comment authors in the moved issue
keepContentMentions: false   # Do not preserve @ mentions in issue content to avoid unwanted notifications

# Label and assignment options
moveLabels: true             # Move labels that exist on the target repository
ignoreMissingLabels: true    # Ignore labels that don't exist on target rather than failing
moveAssignee: true           # Move issue assignee if user exists on target repository

# Repository configuration
# Uncomment and configure aliases for commonly used target repositories
# aliases:
#   main-repo: owner/main-repository
#   archived: owner/archived-issues

# Uncomment to extend configuration from another repository's move.yml file
# _extends: owner/config-repo
