# Configuration for probot-no-response - https://github.com/probot/no-response

# Only apply to issues (default: issue, can be 'pr' or 'both')
type: issue

# Number of days of inactivity before closing an issue for lack of response
daysUntilClose: 14

# Label that requires a response
responseRequiredLabel: 'awaiting user reply'

# Comment to post when closing the issue (set to false to disable)
closeComment: >
  This issue has been automatically closed due to lack of response.
  We need more information to proceed. Please provide the details requested
  to allow us to investigate.

  You can reopen the issue once you have the information ready.
