addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev
      - python3

language: bash

sudo: required

services:
  - docker

env:
  global:
    - CODECOV_TOKEN=77a5a937-8d88-4ff7-be13-405a31ad1bc4
    - PATH=${PATH}:${HOME}/kcov/bin

before_install:
- docker pull alpine:latest
- wget -q --no-check-certificate https://bootstrap.pypa.io/get-pip.py
- sudo -H python3 get-pip.py

install:
- sudo -H pip3 install codecov
- mkdir -p coverage

script:
- sudo -H pip3 install -U pip
- sudo -H pip3 install docker docker-py
- export dfimage=$(docker images alpine --format "{{.ID}}")
- docker run -v /var/run/docker.sock:/var/run/docker.sock --rm laniksj/dfimage $dfimage
- coverage run entrypoint.py $dfimage

after_success:
- bash <(curl -s https://codecov.io/bash)
