name: Dockerfile Image Test

permissions:
  contents: read
  packages: read

on:
  push:
    branches: [ master ]
    paths:
      - Dockerfile
      - dfimage.*
      - pyproject.toml
  pull_request:
    branches: [ master ]
    paths:
      - Dockerfile
      - dfimage.*
      - pyproject.toml
  workflow_dispatch:

env:
  TEST_TAG: laniksj/dfimage:test
  IMAGE_TEST: alpine:latest

jobs:
  dfimage-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build and Export to Docker
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
        with:
          context: .
          load: true
          tags: ${{ env.TEST_TAG }}
      
      - name: Pull Docker Image for Test
        run: docker pull ${{ env.IMAGE_TEST }}

      - name: Test Docker Container
        run: |
          docker run -v /var/run/docker.sock:/var/run/docker.sock --rm ${{ env.TEST_TAG }} ${{ env.IMAGE_TEST }}

      - name: Install with pipx
        run: pipx install .

      - name: Test pipx Install
        run: dfimage laniksj/dfimage:test
